### ISSUE TITLE
Format string without arguments

### ISSUE THREAD

**Issue by Agares** [kiznit/kiznix#1]
https://github.com/kiznit/kiznix/blob/master/src/kernel/acpi.c#L169

You use fatal() here, with %p format, but do not pass any parameter.

**Comment by thierry-kabam** [comment]
Thanks for the feedback. I actually haven't implemented / enabled ACPI yet, so this code doesn't run. You can simply ignore anything in ACPI.c for now.

**Comment by kiznit** [comment]
Thanks for the feedback. I actually haven't implemented / enabled ACPI yet, so this code doesn't run. You can simply ignore anything in ACPI.c for now.
